definitions:
  model.Comment:
    properties:
      created_at:
        type: string
      id:
        type: integer
      message:
        type: string
      photo_id:
        type: integer
      updated_at:
        type: string
      user_id:
        type: integer
    required:
    - message
    type: object
  model.Photo:
    properties:
      caption:
        type: string
      created_at:
        type: string
      id:
        type: integer
      photo_url:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    required:
    - photo_url
    - title
    type: object
  model.RequestComment:
    properties:
      message:
        type: string
      photo_id:
        type: integer
      user_id:
        type: integer
    required:
    - message
    - photo_id
    type: object
  model.RequestPhoto:
    properties:
      caption:
        type: string
      photo_url:
        type: string
      title:
        type: string
    required:
    - photo_url
    - title
    type: object
  model.RequestSocialMedia:
    properties:
      name:
        type: string
      social_media_url:
        type: string
    required:
    - name
    - social_media_url
    type: object
  model.RequestUserLogin:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  model.RequestUserRegister:
    properties:
      age:
        maximum: 130
        minimum: 8
        type: integer
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - age
    - email
    - password
    - username
    type: object
  model.ResponseDeleted:
    properties:
      message:
        type: string
    type: object
  model.ResponseErrorGeneral:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  model.SocialMedia:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      social_media_url:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    required:
    - name
    - social_media_url
    type: object
host: localhost:8080
info:
  contact:
    name: ansharw
  description: This is a sample server MyGram server.
  title: Swagger MyGram API
  version: "1.0"
paths:
  /comment:
    get:
      consumes:
      - application/json
      description: Get all comment by photo id user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Comment'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Get all comment by photo id user
      tags:
      - Comment
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Create comment photo user
      parameters:
      - description: Create Comment photo
        in: body
        name: requestCreate
        required: true
        schema:
          $ref: '#/definitions/model.RequestComment'
      produces:
      - application/json
      - application/x-www-form-urlencoded
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Comment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Create comment photo user
      tags:
      - Comment
  /comment/{commentId}:
    delete:
      consumes:
      - application/json
      description: Delete comment by photo id user
      parameters:
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseDeleted'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Delete comment by photo id user
      tags:
      - Comment
    put:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Update comment by photo id user
      parameters:
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: integer
      - description: Update Comment by photo id user
        in: body
        name: requestUpdate
        required: true
        schema:
          $ref: '#/definitions/model.RequestComment'
      produces:
      - application/json
      - application/x-www-form-urlencoded
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Comment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Update comment by photo id user
      tags:
      - Comment
  /comment/{photoId}:
    get:
      consumes:
      - application/json
      description: Get comment by photo id user
      parameters:
      - description: Comment ID
        in: path
        name: commentId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Comment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Get comment by photo id user
      tags:
      - Comment
  /photo:
    get:
      consumes:
      - application/json
      description: Get all photo user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Photo'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Get all photo user
      tags:
      - Photo
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Create photo user
      parameters:
      - description: Create Photo user
        in: body
        name: requestCreate
        required: true
        schema:
          $ref: '#/definitions/model.RequestPhoto'
      produces:
      - application/json
      - application/x-www-form-urlencoded
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Photo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Create photo user
      tags:
      - Photo
  /photo/{photoId}:
    delete:
      consumes:
      - application/json
      description: Delete photo user
      parameters:
      - description: Photo ID
        in: path
        name: photoId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseDeleted'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Delete photo user
      tags:
      - Photo
    get:
      consumes:
      - application/json
      description: Get photo user
      parameters:
      - description: Photo ID
        in: path
        name: photoId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Photo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Get photo user
      tags:
      - Photo
    put:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Update photo user
      parameters:
      - description: Photo ID
        in: path
        name: photoId
        required: true
        type: integer
      - description: Update Photo user
        in: body
        name: requestUpdate
        required: true
        schema:
          $ref: '#/definitions/model.RequestPhoto'
      produces:
      - application/json
      - application/x-www-form-urlencoded
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Photo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Update photo user
      tags:
      - Photo
  /socialmedia:
    get:
      consumes:
      - application/json
      description: Get all social media user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SocialMedia'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Get all social media user
      tags:
      - Social Media
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Create social media user
      parameters:
      - description: Create Social Media user
        in: body
        name: requestCreate
        required: true
        schema:
          $ref: '#/definitions/model.RequestSocialMedia'
      produces:
      - application/json
      - application/x-www-form-urlencoded
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.SocialMedia'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Create social media user
      tags:
      - Social Media
  /socialmedia/{socialMediaId}:
    delete:
      consumes:
      - application/json
      description: Delete social media user
      parameters:
      - description: Social Media ID
        in: path
        name: socialMediaId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseDeleted'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Delete social media user
      tags:
      - Social Media
    get:
      consumes:
      - application/json
      description: Get social media user
      parameters:
      - description: Social Media ID
        in: path
        name: socialMediaId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SocialMedia'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Get social media user
      tags:
      - Social Media
    put:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Update social media user
      parameters:
      - description: Social Media ID
        in: path
        name: socialMediaId
        required: true
        type: integer
      - description: Update Social Media user
        in: body
        name: requestUpdate
        required: true
        schema:
          $ref: '#/definitions/model.RequestSocialMedia'
      produces:
      - application/json
      - application/x-www-form-urlencoded
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SocialMedia'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      security:
      - JWT: []
      summary: Update social media user
      tags:
      - Social Media
  /users/login:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Login user
      parameters:
      - description: login user
        in: body
        name: requestLogin
        required: true
        schema:
          $ref: '#/definitions/model.RequestUserLogin'
      produces:
      - application/json
      - application/x-www-form-urlencoded
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      summary: Login user
      tags:
      - User
  /users/register:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Register user
      parameters:
      - description: Register user
        in: body
        name: requestRegister
        required: true
        schema:
          $ref: '#/definitions/model.RequestUserRegister'
      produces:
      - application/json
      - application/x-www-form-urlencoded
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ResponseErrorGeneral'
      summary: Register user
      tags:
      - User
securityDefinitions:
  JWT:
    description: 'description: Enter the token with the `Bearer: ` prefix, e.g. "Bearer
      abcde12345".'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
